config/routes.rb
Rails.application.routes.draw do


  resources :plans, only: [:show]
  get '/update_destination' => "call_charges#update_destination", :as => 'update_destination'
  get '/calculate' => "call_charges#calculate_charge", as: "calculate" 
  root 'call_charges#show'

end

app/models/call_charge.rb
class CallCharge < ActiveRecord::Base
  has_many :possible_charges
  has_many :plans, :through => :possible_charges
end

app/models/plan.rb
class Plan < ActiveRecord::Base
  has_many :possible_charges
  has_many :call_charges, :through => :possible_charges
end

app/models/possible_charge.rb
class PossibleCharge < ActiveRecord::Base
  belongs_to :call_charge
  belongs_to :plan
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/call_charges_controller.rb
class CallChargesController < ApplicationController

  def show
    @plans = Plan.all
  end

  def update_destination
    call_destination = CallCharge.where(origin: params[:origin])
    @call_destination = call_destination.map(&:destination)
   
    render :update_destination, layout: false 
  end

  def calculate_charge
    if params[:origin].blank? || params[:destination].blank?
       
      redirect_to root_path, alert: "Você precisa preencher todos os campos"
    else
      @plans = Plan.all
      calculate_charge_without_plan
      calculate_charge_with_plan
      render :show
    end
    
  end

  private
  
  def calculate_charge_without_plan
    calculate = CallCharge.find_by(origin: params[:origin], destination: params[:destination])
    @charge_without_plan = (params[:time_spent].to_f * calculate.price).round(2)
  end

  def calculate_charge_with_plan
    set_call_charge = CallCharge.find_by(origin: params[:origin], destination: params[:destination])
    @calculate_charge = set_call_charge.plans.map do |plan|
      time_charged = params[:time_spent].to_i - plan.time_credit
      unless time_charged > 0
        time_charged = 0
      end
      (time_charged * (set_call_charge.price.to_f * 1.1)).round(2)  
    end
  end

end

app/controllers/plans_controller.rb
class PlansController < ApplicationController

def show
  @plan = Plan.find(params[:id])
  calculate_charge_without_plan
  calculate_charge_with_plan
end

private

  def calculate_charge_without_plan
    calculate = CallCharge.find_by(origin: params[:origin], destination: params[:destination])
    @charge_without_plan = (params[:time_spent].to_f * calculate.price).round(2).to_s
  end

  def calculate_charge_with_plan
    set_call_charge = CallCharge.find_by(origin: params[:origin], destination: params[:destination])
    time_charged = params[:time_spent].to_i - @plan.time_credit
      unless time_charged > 0
        time_charged = 0
      end
    @charge_with_plan = (time_charged * (set_call_charge.price.to_f * 1.1)).round(2).to_s  
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def to_snake_case(name)
    if name.present?
      name.downcase.split.join("_")
    end
  end

  def origins
    CallCharge.distinct.pluck(:origin).reject(&:nil?)
  end

  def destinations(origin = nil)
    return [] if origin.blank?
    CallCharge.distinct.where(origin: origin).pluck(:destination).reject(&:nil?)
  end

  def request_params
    request.params.reject { |k, v| ['commit', 'controller', 'action', 'utf8'].include? k }
  end

end

app/views/call_charges/calculate.html.erb
<div class="without_fale_mais">
<%= @charge_without_plan %>
</div>

app/views/call_charges/show.html.erb
<div class="panel panel-success">
<%= image_tag(asset_path("banner1.jpg"), style: 'width: 100%') %>
  <%= form_tag('/calculate', method: :get) do %>
    <div class="form-group">
      <div class="panel-body">
        <div class="col-xs-6 col-md-2 col-md-offset-2 form-group">
          <div class="text-center" for="origin">Origem</div>
          <div class="input-group">
            <div class="input-group-addon">DDD</div>  
            <%= select_tag(:origin, options_for_select(origins,
                                    selected: params[:origin]), 
                                    { class: "form-control input-lg", id: "origin", include_blank: true }) %>
          </div>
        </div>
        
        <div class="col-xs-6 col-md-2 form-group">
          <div class="text-center" for="destination">Destino</div>
          <div class="input-group">
             <div class="input-group-addon">DDD</div>
             <%= select_tag(:destination, options_for_select(destinations(params[:origin]),
                                          selected: params[:destination]),
                                          { class: "form-control input-lg", id: "destination", include_blank: true }) %>
          </div>
        </div>
      
        <div class="col-xs-6 col-md-2 form-group">
          <div class="text-center" for="timeSpent">Tempo gasto</div>
          <div class="input-group">
            <%= number_field_tag('time_spent', params[:time_spent], min: 0, class: "form-control input-lg text-center") %>
          </div>
        </div>    
      
        <div class="col-xs-4 col-md-2 form-group">
          <div class="text-center invisible" for="calcular">Calcular</div>
            <div class="input-group">
              <%= submit_tag("calcular", class: "btn-success btn-lg") %>
            </div>
          </div>
        </div>

      </div>
    </div>
  <% end %>
</div>

<% if @calculate_charge.present? %>
  <div class="without_fale_mais col-xs-12 col-md-3 text-center">
    <div class="panel panel-default">
      <div class="panel-heading">Sem Fale Mais</div>
      <div class="panel-body">
        <p><%= number_to_currency(@charge_without_plan) %></p>
        Veja mais detalhes!
      </div>
    </div>
  </div>
  <% @plans.each_with_index do |plan, i| %>
      <%= content_tag :div, plan, class: "col-xs-12 col-md-3 text-center plans #{to_snake_case(plan.name)}" do %>
        <div class="panel panel-success">
          <div class="panel-heading"><%= plan.name %></div>
          <div class="panel-body">
            <p><%= number_to_currency(@calculate_charge[i]) %></p>
            <p><%= link_to 'Veja mais detalhes!', plan_path(plan, request_params) %>
          </div>
        </div> 
      <% end %>
  <% end %>
<% end %>


<script>
  $(document).ready(function() {
    $('#origin').change(function() {
      $("#destination option").remove();
      $.ajax({
        url: "<%= update_destination_path %>",
        data: { origin: $('#origin').val() },
        dataType: "html"
      }).success(function(data) {
        $("#destination").append(data);
      });
    });
  });
</script>

app/views/call_charges/update_destination.html.erb
<% @call_destination.each do |destination| %>
  <option value = <%= destination %>> <%= destination %> </option> 
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Telzir</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <%= render 'shared/navbar' %>
  </header>
  <main>
  <div class="container">
    <% flash.each do |type, message| %>
      <div class="alert alert-danger text-center" role="alert">
        <%= message %>
      </div>
    <% end %>
    <%= yield %>
  </div>
  </main>
  <footer>
  </footer>
</body>
</html>

app/views/plans/show.html.erb
<div class="container-fluid">
  <div class="col-xs-12 col-md-12 text-center">
    <div class="panel panel-success">
      <div class="panel-heading"><h2><%= @plan.name %></h2></div>
        <div class="panel-body text-info">
          <h4>
            <p><%= @plan.description %></p>
            <p>Confira abaixo a comparação!</p>
          </h4>
          <div id="container" style="width:100%; height:400px;"></div>
          <%= link_to 'Voltar', request.referer %>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
  $(function () {
    var ChargeWithoutPlan = <%= @charge_without_plan %>
    var ChargeWithPlan = <%= @charge_with_plan %>
    if (ChargeWithoutPlan > ChargeWithPlan ) {
      maxval = ChargeWithoutPlan
    } else { 
      maxval = ChargeWithPlan 
    }
    $('#container').highcharts({
      chart: {
        type: 'column'
      },
      title: {
        text: ''
      },
      xAxis: {
        categories: ['']
      },
      yAxis: {
        min: 0,
        max: maxval ,
        title: { text: 'Preço ( R$ )' },
      },
      tooltip: {
        formatter: function () {
          return '<b>' + this.series.name + '</b><br/>' + "Preço: R$" + Highcharts.numberFormat(this.y, 2);
        }
      },
      credits: {
        enabled: false
      },
      exporting: {
        enabled: false
      },
      series: [
        {
          name: 'Sem Fale Mais',
          data: [ChargeWithoutPlan],
        },
        {
          name: 'Com Fale Mais',
          data: [ChargeWithPlan]
        }
      ]
    });
  });
</script>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <%= link_to 'Telzir', root_path, class: 'navbar-brand' %>
    </div>
  </div>
</nav>